// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/index.php": {
            "post": {
                "description": "Receives status updates from MyFatoorah via the route query parameter.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "webhooks"
                ],
                "summary": "MyFatoorah Webhook",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Must be: extension/myfatoorah/payment/myfatoorah.webhook",
                        "name": "route",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "message: Route not found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/invoices": {
            "get": {
                "description": "Retrieves all invoices with their nested session and transaction history.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "invoices"
                ],
                "summary": "List all invoices",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/hello-go-project_myfatoorah_internal_models.Invoice"
                            }
                        }
                    },
                    "500": {
                        "description": "error: database error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Creates an internal invoice and generates a MyFatoorah payment link.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "invoices"
                ],
                "summary": "Initiate Hosted Payment (Invoice/Link)",
                "parameters": [
                    {
                        "description": "Invoice Initiation Details",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/hello-go-project_myfatoorah_internal_dto.CreatePaymentRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/hello-go-project_myfatoorah_internal_dto.CreatePaymentResponse"
                        }
                    }
                }
            }
        },
        "/invoices/{id}": {
            "get": {
                "description": "Retrieves an invoice by its UUID, including all associated payment sessions and their transaction attempts.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "invoices"
                ],
                "summary": "Get a specific invoice",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Invoice UUID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/hello-go-project_myfatoorah_internal_models.Invoice"
                        }
                    },
                    "404": {
                        "description": "error: Invoice not found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/sessions": {
            "get": {
                "tags": [
                    "sessions"
                ],
                "summary": "Get All Sessions with Transactions",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/hello-go-project_myfatoorah_internal_models.Session"
                            }
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "sessions"
                ],
                "summary": "Create a new payment session",
                "parameters": [
                    {
                        "description": "Session Details",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/hello-go-project_myfatoorah_internal_dto.CreateSessionRequest"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/transactions": {
            "get": {
                "description": "Retrieves a list of all payment transactions with search, filter, and sorting.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "transactions"
                ],
                "summary": "Get All Transactions",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Search by Order ID or Reference",
                        "name": "search",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by Status (e.g., SUCCESS, FAILED)",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Field to sort by (default: created_at)",
                        "name": "sort_by",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Order direction (asc, desc)",
                        "name": "order",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/hello-go-project_myfatoorah_internal_models.Transaction"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "hello-go-project_myfatoorah_internal_dto.CreatePaymentRequest": {
            "type": "object",
            "required": [
                "amount"
            ],
            "properties": {
                "amount": {
                    "type": "number",
                    "example": 100
                },
                "country_code": {
                    "type": "string",
                    "example": "20"
                },
                "customer_name": {
                    "description": "Optional fields with defaults",
                    "type": "string",
                    "example": "Diaa Dawood"
                },
                "email": {
                    "type": "string",
                    "example": "diaadawood.mas@gmail.com"
                },
                "expiry_date": {
                    "type": "string"
                },
                "mobile_number": {
                    "type": "string",
                    "example": "1015433746"
                },
                "order_id": {
                    "type": "string",
                    "example": "ORD-2026-001"
                }
            }
        },
        "hello-go-project_myfatoorah_internal_dto.CreatePaymentResponse": {
            "type": "object",
            "properties": {
                "invoice_id": {
                    "type": "integer",
                    "example": 6646004
                },
                "message": {
                    "type": "string",
                    "example": "Payment link generated successfully"
                },
                "payment_url": {
                    "type": "string",
                    "example": "https://demo.myfatoorah.com/..."
                }
            }
        },
        "hello-go-project_myfatoorah_internal_dto.CreateSessionRequest": {
            "type": "object",
            "required": [
                "amount"
            ],
            "properties": {
                "amount": {
                    "type": "number"
                },
                "customer_id": {
                    "description": "Nullable",
                    "type": "string"
                },
                "order_id": {
                    "description": "Nullable",
                    "type": "string"
                },
                "redirection_url": {
                    "type": "string"
                },
                "session_expiry": {
                    "description": "Nullable UTC time",
                    "type": "string"
                }
            }
        },
        "hello-go-project_myfatoorah_internal_models.Invoice": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "currency": {
                    "type": "string"
                },
                "customer_email": {
                    "type": "string"
                },
                "customer_name": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "order_id": {
                    "description": "Internal ID",
                    "type": "string"
                },
                "status": {
                    "description": "PENDING, PAID, EXPIRED",
                    "type": "string"
                },
                "total_value": {
                    "type": "number"
                },
                "transactions": {
                    "description": "Relationships",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/hello-go-project_myfatoorah_internal_models.Transaction"
                    }
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "hello-go-project_myfatoorah_internal_models.Session": {
            "type": "object",
            "properties": {
                "amount": {
                    "description": "Order Details",
                    "type": "number"
                },
                "created_at": {
                    "description": "Metadata",
                    "type": "string"
                },
                "currency": {
                    "type": "string"
                },
                "customer_email": {
                    "type": "string"
                },
                "customer_name": {
                    "description": "Customer Details (Mapped from the Customer object in response)",
                    "type": "string"
                },
                "customer_reference": {
                    "description": "This is your internal \"456123789\"",
                    "type": "string"
                },
                "encryption_key": {
                    "type": "string"
                },
                "id": {
                    "description": "Internal Primary Key",
                    "type": "string"
                },
                "invoice_id": {
                    "type": "string"
                },
                "operation_type": {
                    "description": "e.g., \"PAY\"",
                    "type": "string"
                },
                "session_expiry": {
                    "type": "string"
                },
                "session_id": {
                    "description": "MyFatoorah Data",
                    "type": "string"
                },
                "transactions": {
                    "description": "Relations",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/hello-go-project_myfatoorah_internal_models.Transaction"
                    }
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "hello-go-project_myfatoorah_internal_models.Transaction": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "customer_id": {
                    "type": "string"
                },
                "error_code": {
                    "type": "string"
                },
                "error_message": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "invoice_id": {
                    "description": "Now a regular index: allows the link creation + multiple payment attempts",
                    "type": "string"
                },
                "invoice_value": {
                    "description": "Using decimal for money is safer than float64 in SQL",
                    "type": "number"
                },
                "merchant_id": {
                    "type": "string"
                },
                "mf_invoice_id": {
                    "type": "integer"
                },
                "order_id": {
                    "type": "string"
                },
                "reference": {
                    "description": "Unique anchor: prevents the same PaymentId from duplicating",
                    "type": "string"
                },
                "session_id": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "MyFatoorah API",
	Description:      "This is a sample server for MyFatoorah.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
