// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/customers": {
            "post": {
                "description": "Accepts customer details and performs an upsert. Returns the customer ID and info.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Customers"
                ],
                "summary": "Create or Update a Customer",
                "parameters": [
                    {
                        "description": "Customer Details",
                        "name": "customer",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/hello-go-project_myfatoorahInstallment_internal_dto_request.CreateCustomerRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/hello-go-project_myfatoorahInstallment_internal_dto_response.StandardResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/hello-go-project_myfatoorahInstallment_internal_dto_response.CustomerResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Invalid Input",
                        "schema": {
                            "$ref": "#/definitions/hello-go-project_myfatoorahInstallment_internal_dto_response.StandardResponse"
                        }
                    },
                    "500": {
                        "description": "Database Error",
                        "schema": {
                            "$ref": "#/definitions/hello-go-project_myfatoorahInstallment_internal_dto_response.StandardResponse"
                        }
                    }
                }
            }
        },
        "/customers/getall": {
            "get": {
                "description": "Retrieves customers with a global search (name/email/mobile) and dynamic sorting.",
                "tags": [
                    "Customers"
                ],
                "summary": "Get All Customers",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Page number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page size",
                        "name": "size",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Search by name, email, or mobile",
                        "name": "search",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Sort column (default: created_at)",
                        "name": "sort",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Sort direction (asc/desc)",
                        "name": "sort_dir",
                        "in": "query"
                    }
                ],
                "responses": {}
            }
        },
        "/index.php": {
            "post": {
                "security": [
                    {
                        "MyFatoorahAuth": []
                    }
                ],
                "description": "Receives payment status updates. If 'Captured', it creates the Installment, Transaction, and updates the Invoice.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Webhooks"
                ],
                "summary": "Handle MyFatoorah Webhook",
                "responses": {}
            }
        },
        "/sessions/execute": {
            "post": {
                "description": "Receives Session B from the frontend after card tokenization. Updates the existing record with the new ExecutionSID and amount.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Sessions"
                ],
                "summary": "Tokenize and Update Session",
                "parameters": [
                    {
                        "description": "Execution Details (Session B)",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/hello-go-project_myfatoorahInstallment_internal_dto_request.ExecuteRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "message: Session updated successfully, status: TOKENIZED",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "error: Invalid request payload",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "error: Session not found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "error: Failed to update session",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/sessions/initiate": {
            "post": {
                "description": "Calls MyFatoorah InitiateSession, stores the intent in PaymentSessions table, and returns Session A.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Sessions"
                ],
                "summary": "Initiate Payment Session",
                "parameters": [
                    {
                        "description": "Session Details",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/hello-go-project_myfatoorahInstallment_internal_dto_request.CreateSessionRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/hello-go-project_myfatoorahInstallment_internal_models.PaymentSession"
                        }
                    },
                    "400": {
                        "description": "Invalid Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "API or Database Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "hello-go-project_myfatoorahInstallment_internal_dto_request.CreateCustomerRequest": {
            "type": "object",
            "required": [
                "email",
                "name",
                "phone"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                }
            }
        },
        "hello-go-project_myfatoorahInstallment_internal_dto_request.CreateSessionRequest": {
            "type": "object",
            "properties": {
                "customer_id": {
                    "type": "string"
                },
                "payment_method_id": {
                    "type": "number"
                }
            }
        },
        "hello-go-project_myfatoorahInstallment_internal_dto_request.ExecuteRequest": {
            "type": "object",
            "properties": {
                "InvoiceValue": {
                    "type": "number"
                },
                "OriginalSessionID": {
                    "type": "string"
                },
                "RecurringModel": {
                    "type": "object",
                    "properties": {
                        "IntervalDays": {
                            "type": "integer"
                        },
                        "Iteration": {
                            "type": "integer"
                        },
                        "RecurringType": {
                            "type": "string"
                        },
                        "RetryCount": {
                            "type": "integer"
                        }
                    }
                },
                "SessionId": {
                    "description": "This is the Session B from frontend",
                    "type": "string"
                }
            }
        },
        "hello-go-project_myfatoorahInstallment_internal_dto_response.CustomerResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                }
            }
        },
        "hello-go-project_myfatoorahInstallment_internal_dto_response.StandardResponse": {
            "type": "object",
            "properties": {
                "data": {},
                "message": {
                    "type": "string"
                }
            }
        },
        "hello-go-project_myfatoorahInstallment_internal_models.Customer": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                },
                "sessions": {
                    "description": "Relationship: One customer can have many payment sessions",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/hello-go-project_myfatoorahInstallment_internal_models.PaymentSession"
                    }
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "hello-go-project_myfatoorahInstallment_internal_models.PaymentSession": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "number"
                },
                "created_at": {
                    "type": "string"
                },
                "customer": {
                    "$ref": "#/definitions/hello-go-project_myfatoorahInstallment_internal_models.Customer"
                },
                "customer_id": {
                    "type": "string"
                },
                "execution_sid": {
                    "description": "Session B: From Callback (Frontend)",
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "interval_days": {
                    "type": "integer"
                },
                "invoice_id": {
                    "type": "integer"
                },
                "status": {
                    "description": "PENDING, TOKENIZED, COMPLETED, FAILED",
                    "type": "string"
                },
                "total_iterations": {
                    "description": "Installment Parameters (Stored here until the first payment succeeds)",
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "MyFatoorah Installment API",
	Description:      "This is a sample server for MyFatoorah.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
