basePath: /
definitions:
  hello-go-project_myfatoorahInstallment_internal_dto_request.CreateSessionRequest:
    properties:
      customer_id:
        type: string
      payment_method_id:
        type: number
    type: object
  hello-go-project_myfatoorahInstallment_internal_models.PaymentSession:
    properties:
      amount:
        type: number
      created_at:
        type: string
      execution_sid:
        description: 'Session B: From Callback (Frontend)'
        type: string
      id:
        type: string
      initiate_sid:
        description: 'Session A: From InitiateSession (Backend)'
        type: string
      interval_days:
        type: integer
      status:
        description: PENDING, TOKENIZED, COMPLETED, FAILED
        type: string
      total_iterations:
        description: Installment Parameters (Stored here until the first payment succeeds)
        type: integer
      user_id:
        type: string
    type: object
info:
  contact: {}
  description: This is a sample server for MyFatoorah.
  title: MyFatoorah Installment API
  version: "1.0"
paths:
  /payments/initiate:
    post:
      consumes:
      - application/json
      description: Calls MyFatoorah InitiateSession, stores the intent in PaymentSessions
        table, and returns Session A.
      parameters:
      - description: Session Details
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/hello-go-project_myfatoorahInstallment_internal_dto_request.CreateSessionRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/hello-go-project_myfatoorahInstallment_internal_models.PaymentSession'
        "400":
          description: Invalid Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: API or Database Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Initiate Payment Session
      tags:
      - Payments
swagger: "2.0"
